# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# scripts to run before build
before_build:
  - nuget restore

build:
  project: Kentor.AuthServices.sln

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder to avoid repeated downloads for nuget restore
